### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by swarr2** [socketio/socket.io-website#95]
In the terminal (Win 10) I get The error below.  My code is identical to the first example.

chat>node index2.js
internal/modules/cjs/loader.js:630
    throw new ERR_INVALID_ARG_TYPE('id', 'string', id);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received type undefined
    at Module.require (internal/modules/cjs/loader.js:630:11)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (D:\chat\index2.js:2:12)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
